baseURL = "https://example.com"
title = "Yiğit Kolat"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = false

[params]
    # The name to display as main title in the home page
    mainpagetitle = "YİĞİT KOLAT | COMPOSER"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Welcome! Please use the menu above. The slow loading is not a bug, it's a feature." 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = ""

    # The name to display in the copyright section in the footer
    copyrightname = "Yiğit Kolat"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = false

    showdate = false

    # Urls for social networks
    facebook = ""
    twitter = ""
    linkedin = ""
    github = "https://www.youtube.com/channel/UCGrkqx-0aSupn8eHfroxthg"
    gitlab = "https://soundcloud.com/ykolat"
    
    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 0.3

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Yiğit Kolat"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = ""

    # Text to go before copyright information
    prefix = ""

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = ""

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "works" # An unique identifier for the button
    name = "Works"       # A display name for the button
    url = "/works/"      # The path to the content. It can lead to a single page (like here)
    weight = 20          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"       # The path can lead to a content folder too.
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"       # The path can lead to a content folder too.
    weight = 40

[taxonomies]
category = "categories"
tag = ""

[markup.goldmark.renderer]
unsafe= true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true